import { WeatherConditionType } from '../types/weather';

export type WeatherVisualCondition = 'clear' | 'partly_cloudy' | 'cloudy' | 'rain' | 'heavy_rain' | 'thunderstorm' | 'snow' | 'fog' | 'wind' | 'unknown';
export type WeatherDayPhase = 'day' | 'sunset' | 'night';
export interface WeatherVisualConfig { condition: WeatherVisualCondition; label: string; accent: string; videoSrc?: string; posterSrc?: string; effect: 'sun' | 'clouds' | 'rain' | 'heavy-rain' | 'storm' | 'snow' | 'fog' | 'wind' | 'stars' | 'neutral'; }
export const WEATHER_VISUALS: Record<WeatherVisualCondition, WeatherVisualConfig> = {
  clear: { condition: 'clear', label: 'Clear sky', accent: '#f59e0b', effect: 'sun' }, partly_cloudy: { condition: 'partly_cloudy', label: 'Partly cloudy', accent: '#38bdf8', effect: 'clouds' }, cloudy: { condition: 'cloudy', label: 'Cloudy', accent: '#94a3b8', effect: 'clouds' }, rain: { condition: 'rain', label: 'Rain', accent: '#38bdf8', effect: 'rain' }, heavy_rain: { condition: 'heavy_rain', label: 'Heavy rain', accent: '#60a5fa', effect: 'heavy-rain' }, thunderstorm: { condition: 'thunderstorm', label: 'Thunderstorm', accent: '#c084fc', effect: 'storm' }, snow: { condition: 'snow', label: 'Snow', accent: '#bae6fd', effect: 'snow' }, fog: { condition: 'fog', label: 'Fog', accent: '#cbd5e1', effect: 'fog' }, wind: { condition: 'wind', label: 'Windy', accent: '#67e8f9', effect: 'wind' }, unknown: { condition: 'unknown', label: 'Weather', accent: '#38bdf8', effect: 'neutral' },
};
const parseHour = (localTime?: string) => { const match = localTime?.match(/\b(\d{1,2})(?::\d{2})?\s*(AM|PM)?\b/i); if (!match) return 12; let hour = Number(match[1]); const meridiem = match[2]?.toUpperCase(); if (meridiem === 'PM' && hour < 12) hour += 12; if (meridiem === 'AM' && hour === 12) hour = 0; return hour; };
export const getDayPhase = (localTime?: string): WeatherDayPhase => { const hour = parseHour(localTime); if (hour >= 5 && hour < 7 || hour >= 17 && hour < 19) return 'sunset'; return hour >= 7 && hour < 17 ? 'day' : 'night'; };
export const normalizeWeatherCondition = (condition?: string): WeatherVisualCondition => { const normalized = condition?.toLowerCase().replace(/[_\s]+/g, '-') || ''; if (normalized.includes('thunder') || normalized.includes('storm')) return 'thunderstorm'; if (normalized.includes('heavy-rain')) return 'heavy_rain'; if (normalized.includes('rain') || normalized.includes('drizzle')) return 'rain'; if (normalized.includes('snow') || normalized.includes('flurr') || normalized.includes('ice')) return 'snow'; if (normalized.includes('fog') || normalized.includes('mist') || normalized.includes('haze')) return 'fog'; if (normalized.includes('wind')) return 'wind'; if (normalized.includes('partly-cloudy')) return 'partly_cloudy'; if (normalized.includes('cloud') || normalized.includes('overcast')) return 'cloudy'; if (normalized.includes('clear') || normalized.includes('sun')) return 'clear'; return 'unknown'; };
export const getWeatherVisualState = (condition?: WeatherConditionType | string, localTime?: string) => { const normalizedCondition = normalizeWeatherCondition(condition); const phase = getDayPhase(localTime); return { ...WEATHER_VISUALS[normalizedCondition], phase, stateKey: `${normalizedCondition}-${phase}` }; };
