import { UnitType, WeatherDataBundle } from '../types/weather';
export interface LocationSearchResult { id: string; name: string; region: string; country: string; countryCode?: string; featureType?: string; latitude: number; longitude: number; timezone: string; tempC: number | null; conditionText: string; conditionIcon: string; }
export class WeatherService {
  private static readonly defaultLocation: LocationSearchResult = { id: '26.91240,75.78730', name: 'Jaipur', region: 'Rajasthan', country: 'India', countryCode: 'IN', latitude: 26.9124, longitude: 75.7873, timezone: 'Asia/Kolkata', tempC: null, conditionText: 'Select to load forecast', conditionIcon: 'cloudy' };
  private static readonly locations = new Map<string, LocationSearchResult>([[WeatherService.defaultLocation.id, WeatherService.defaultLocation]]);
  public static async getWeatherData(locationId = WeatherService.defaultLocation.id): Promise<WeatherDataBundle> { const location = this.locations.get(locationId) || this.parseCoordinateLocation(locationId); if (!location) throw new Error('LOCATION_NOT_FOUND'); const params = new URLSearchParams({ lat: String(location.latitude), lon: String(location.longitude), name: location.name, region: location.region, country: location.country }); return this.request<WeatherDataBundle>(`/api/weather/overview?${params}`); }
  public static async searchLocations(query: string): Promise<LocationSearchResult[]> { if (!query.trim()) return []; const data = await this.request<{ results: LocationSearchResult[] }>(`/api/locations/search?q=${encodeURIComponent(query.trim())}`); data.results.forEach((location) => this.locations.set(location.id, location)); return data.results; }
  public static getPopularLocations(): LocationSearchResult[] { return [WeatherService.defaultLocation]; }
  public static async reverseLocation(latitude: number, longitude: number): Promise<LocationSearchResult> { const data = await this.request<{ location: LocationSearchResult }>(`/api/locations/reverse?lat=${latitude}&lon=${longitude}`); const location = { ...data.location, tempC: null, conditionText: 'Select to load forecast', conditionIcon: 'cloudy' }; this.locations.set(location.id, location); return location; }
  public static formatTemp(tempC: number, unit: UnitType): string { return unit === 'fahrenheit' ? `${Math.round((tempC * 9) / 5 + 32)}°` : `${Math.round(tempC)}°`; }
  public static formatSpeed(kph: number, unit: UnitType): string { return unit === 'fahrenheit' ? `${Math.round(kph * 0.621371)} mph` : `${Math.round(kph)} km/h`; }
  private static parseCoordinateLocation(locationId: string): LocationSearchResult | null { const [latitude, longitude] = locationId.split(',').map(Number); if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) return null; return { ...WeatherService.defaultLocation, id: locationId, name: 'Selected location', region: '', country: '', latitude, longitude }; }
  private static async request<T>(path: string): Promise<T> { const response = await fetch(path); const payload = await response.json() as T & { error?: { message?: string } }; if (!response.ok) throw new Error(payload.error?.message || 'Weather request failed'); return payload; }
}
