export type WeatherConditionType = 'clear-day' | 'clear-night' | 'partly-cloudy-day' | 'partly-cloudy-night' | 'cloudy' | 'overcast' | 'fog' | 'drizzle' | 'rain' | 'heavy-rain' | 'thunderstorm' | 'snow' | 'windy';
export type AlertSeverity = 'info' | 'watch' | 'warning' | 'severe';
export type AQICategory = 'Good' | 'Moderate' | 'Unhealthy for Sensitive Groups' | 'Unhealthy' | 'Very Unhealthy' | 'Hazardous';
export type UnitType = 'celsius' | 'fahrenheit';
export interface LocationCoordinates { lat: number; lon: number; }
export interface LocationData { id: string; name: string; region: string; country: string; isCurrent?: boolean; coordinates: LocationCoordinates; timezone: string; localTime: string; countryCode?: string; featureType?: string; population?: number; }
export interface CurrentWeather { temperatureC: number; feelsLikeC: number; condition: WeatherConditionType; conditionText: string; highC: number; lowC: number; humidityPercent: number; windKph: number; windDirection: string; windDegree: number; windGustKph: number; uvIndex: number; visibilityKm: number; pressureHpa: number; pressureTrend: 'rising' | 'falling' | 'steady'; dewPointC: number; cloudCoverPercent: number; precipitationMm: number; precipitationProbability: number; lastUpdated: string; microSummary: string; apparentTemperature?: number; }
export interface HourlyForecastItem { time: string; fullTime: string; tempC: number; condition: WeatherConditionType; conditionText: string; pop: number; precipMm: number; windKph: number; uvIndex: number; }
export interface DailyForecastItem { dayName: string; date: string; condition: WeatherConditionType; conditionText: string; minTempC: number; maxTempC: number; pop: number; rainMm: number; windKph: number; uvIndex: number; summary: string; }
export interface PrecipitationInterval { minute: string; intensity: 'none' | 'light' | 'moderate' | 'heavy'; probability: number; amountMm: number; }
export interface WeatherAlert { id: string; title: string; severity: AlertSeverity; headline: string; window: string; expectedPrecipitation?: string; source: string; description: string; recommendedAction: string; type?: 'official' | 'generated'; issuedAt?: string; expiresAt?: string; }
export interface SmartInsight { id: string; type: 'precip' | 'storm' | 'commute' | 'unusual' | 'lifestyle'; title: string; detail: string; confidence?: number; confidenceLabel?: string; actionText: string; actionType: 'precip' | 'radar' | 'hourly' | 'aqi' | 'lifestyle'; badge: string; iconName: string; }
export interface AirQualityData { aqi: number; category: AQICategory; dominantPollutant: string; pm25: number; pm10: number; o3: number; no2: number; so2: number; co: number; healthRecommendations: { general: string; sensitiveGroups: string; outdoorActivity: string; }; }
export interface ActivityRecommendation { activity: string; category: 'sports' | 'leisure' | 'practical'; score: 'optimal' | 'good' | 'moderate' | 'avoid'; label: string; reason: string; icon: string; }
export interface SunMoonCycle { sunrise: string; sunset: string; dawn: string; dusk: string; daylightRemaining: string; goldenHour: string; moonPhase: string; moonIllumination: number; }
export interface WeatherDataBundle { location: LocationData; current: CurrentWeather; intelligence: SmartInsight[]; alerts: WeatherAlert[]; hourly: HourlyForecastItem[]; daily: DailyForecastItem[]; precipitationTimeline: PrecipitationInterval[]; airQuality: AirQualityData | null; activities: ActivityRecommendation[]; sunMoon: SunMoonCycle; radarTimestamp: string; status: 'live' | 'stale' | 'offline'; metadata?: { provider: string; fetchedAt: string; sourceUpdatedAt?: string; cache: 'hit' | 'miss' | 'stale'; officialAlerts: 'available' | 'unavailable'; }; }
